Add direct download of apks

diff --git a/src/scripts/autoextract b/src/scripts/autoextract
--- a/src/scripts/autoextract
+++ b/src/scripts/autoextract
@@ -18,12 +18,10 @@ description() {
 	echo "	-v	print more information; specify twice for debug output"
 }
 
-# shbuild replace common.sh
 # shellcheck source=./common.sh
 if [ -r "$(dirname "$0")"/common.sh ]; then
 	. "$(dirname "$0")"/common.sh
 fi
-# shbuild end replace common.sh
 
 DEBUG=""
 VERBOSE=""
@@ -101,6 +99,57 @@ if ! mkdir -p -- "$MFFOUTPUTDIR" >"$DEBUGOUT" 2>&1; then
 	exit 1
 fi
 MFFOUTPUTDIR="$(getdir "$MFFOUTPUTDIR")"
+
+echo "Getting MFF from the Google Play Store..." >"$VERBOSEOUT"
+if ! PYTHON3="$(which python3)" >"$DEBUGOUT" 2>&1; then
+	echo "Error: unable to locate python3 executable" >&2
+	exit 1
+fi
+if ! "$PYTHON3" -m venv "$MFFTEMPDIR/python"; then
+	echo "Error: unable to create temporary python environment" >&2
+	exit 1
+fi
+if [ -r "$MFFTEMPDIR/python/bin/activate" ]; then
+	# shellcheck disable=SC1091
+	. "$MFFTEMPDIR"/python/bin/activate
+	if ! python; then
+		echo "Error: could not run python3." >&2
+		exit 1
+	fi <<EOF
+import string
+import sys
+if sys.prefix == sys.base_prefix:
+    print( "Not in a virtual environment", file=sys.stderr)
+    exit(1)
+if not sys.prefix.startswith( "$MFFTEMPDIR" ) and not sys.prefix.startswith( "/private$MFFTEMPDIR" ):
+    print( "Not running in $MFFTEMPDIR", file=sys.stderr)
+    print( "(sys.prefix=" + sys.prefix +")")
+    exit(1)
+if sys.version_info.major != 3:
+    print( "Not running in Python 3", file=sys.stderr)
+    exit(1)
+EOF
+fi
+
+if ! pip3 install --upgrade --force-reinstall gplaydl==1.3.5 >"$DEBUGOUT" 2>&1 \
+	|| ! echo "Enter a Google account username and password to download MFF." \
+	|| ! echo "(You'll need an app password to allow access to this program.)" \
+	|| ! printf 'Google Email: ' \
+	|| ! gplaydl configure >"$DEBUGOUT" \
+	|| ! gplaydl download --packageId com.netmarble.mherosgb --path "$MFFTEMPDIR" >"$DEBUGOUT"; then
+	echo "Unable to download MFF" >&2
+	exit 1
+fi
+BASEAPK="$MFFTEMPDIR"/com.netmarble.mherosgb.apk
+for file in "$MFFTEMPDIR"/com.netmarble.mherosgb/config.*.apk; do
+	SPLITAPK="$file"
+done
+if [ ! -f "$BASEAPK" ] || [ ! -f "$SPLITAPK" ]; then
+	echo "MFF download files are invalid" >&2
+	exit 1
+fi
+mkdir -p "$MFFOUTPUTDIR"/apks
+mv "$BASEAPK" "$SPLITAPK" "$MFFOUTPUTDIR"/apks
 
 MFF_ANDROID_SDK_URL_BASE='https://dl.google.com/android/repository/'
 if [ x = "${MFF_OS}x" ]; then
